import type { Metadata } from "next";
import { moderateListingAction } from "@/features/admin/operations.actions";
import { prisma } from "@/lib/prisma";

export const metadata: Metadata = { title: "Marketplace moderation" };

export default async function MarketplaceModerationPage({ searchParams }: { searchParams: Promise<{ notice?: string; error?: string }> }) {
  const [query, listings, recentSales] = await Promise.all([searchParams, prisma.marketListing.findMany({ where: { status: "ACTIVE" }, include: { seller: true, card: { include: { definition: { include: { set: true } } } } }, orderBy: { createdAt: "desc" }, take: 100 }), prisma.marketSale.findMany({ include: { buyer: true, seller: true, card: { include: { definition: true } } }, orderBy: { createdAt: "desc" }, take: 30 })]);
  return <main className="admin-page"><div className="admin-title"><div><p>Collector safety</p><h1>Marketplace moderation</h1></div><span>Removing a listing does not move Crowns or ownership</span></div>{query.notice && <p className="admin-notice">{query.notice}</p>}{query.error && <p className="admin-error">{query.error}</p>}<section className="admin-panel moderation-list"><div className="panel-heading"><span>01</span><div><h2>Active listings</h2><p>{listings.length} listings available to players.</p></div></div>{listings.map((listing) => <details key={listing.id}><summary><span>{listing.card.definition.name} · {listing.card.definition.set.code} · Serial #{String(listing.card.serialNumber).padStart(6, "0")}</span><strong>{listing.price.toLocaleString()} Crowns</strong><small>{listing.seller.displayName ?? "Collector"}</small></summary><form action={moderateListingAction} className="admin-form"><input name="listingId" type="hidden" value={listing.id} /><label>Moderation reason<textarea minLength={10} maxLength={300} name="reason" required /></label><label>Type CONFIRM<input name="confirmation" required /></label><button className="button button-primary">Remove listing</button></form></details>)}</section><section className="admin-panel admin-sales"><div className="panel-heading"><span>02</span><div><h2>Recent immutable sales</h2><p>Completed sales cannot be edited or deleted.</p></div></div>{recentSales.map((sale) => <div key={sale.id}><time>{sale.createdAt.toLocaleString("en-US")}</time><span>{sale.card.definition.name}</span><small>{sale.seller.displayName ?? "Seller"} → {sale.buyer.displayName ?? "Buyer"}</small><strong>{sale.price.toLocaleString()} Crowns</strong></div>)}</section></main>;
}
