import type { Metadata } from "next";
import { operateMarketAction, saveMarketAction } from "@/features/betting/betting.actions";
import { oddsLabel } from "@/features/betting/betting.logic";
import { prisma } from "@/lib/prisma";
import { SearchableSelect } from "@/components/searchable-select";

export const metadata: Metadata = { title: "Fight betting" };

export default async function AdminBettingPage({ searchParams }: { searchParams: Promise<{ notice?: string; error?: string }> }) {
  const [{ notice, error }, fights, markets] = await Promise.all([
    searchParams,
    prisma.fight.findMany({ where: { status: "SCHEDULED" }, include: { event: true, redFighter: true, blueFighter: true, market: true }, orderBy: { event: { startsAt: "asc" } }, take: 100 }),
    prisma.betMarket.findMany({ include: { fight: { include: { event: true, redFighter: true, blueFighter: true } }, _count: { select: { bets: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
  ]);
  return <main className="admin-page"><div className="admin-title"><div><p>Economy operations</p><h1>Fight betting</h1></div><span>Odds changes only affect new bets</span></div>{notice && <p className="admin-notice" role="status">{notice}</p>}{error && <p className="admin-error" role="alert">{error}</p>}<div className="live-admin-layout"><section className="admin-panel"><div className="panel-heading"><span>01</span><div><h2>Open or price a market</h2><p>Decimal odds represent total return, including stake.</p></div></div><form action={saveMarketAction} className="admin-form"><SearchableSelect name="fightId" label="Scheduled fight" options={fights.map((fight) => ({ value: fight.id, label: `${fight.redFighter.name} vs ${fight.blueFighter.name}`, details: `${fight.event.title} · ${fight.event.startsAt.toLocaleDateString("en-US")}` }))} searchPlaceholder="Search event or fighter…" /><div className="form-row"><label>Red odds<input min="1" max="100" name="redOdds" step="0.01" type="number" defaultValue="1.90" /></label><label>Blue odds<input min="1" max="100" name="blueOdds" step="0.01" type="number" defaultValue="1.90" /></label></div><button className="button button-primary" type="submit">Save market</button></form></section><section className="admin-panel"><div className="panel-heading"><span>02</span><div><h2>Settlement rules</h2><p>Lock at fight start. Settle only after an official red or blue result. Void returns every stake.</p></div></div><p className="admin-guidance">Draws, no contests, cancellations, and abandoned fights must be voided. Settlement and refunds are idempotent and recorded in the admin audit log.</p></section></div><section className="admin-panel admin-live-fights"><div className="panel-heading"><span>03</span><div><h2>Market operations</h2><p>Review state, accepted bets, and current prices.</p></div></div>{markets.length === 0 ? <p className="admin-guidance">No markets have been created.</p> : markets.map((market) => <form action={operateMarketAction} className="market-control" key={market.id}><input name="marketId" type="hidden" value={market.id} /><div><small>{market.fight.event.title} · {market._count.bets} bets</small><strong>{market.fight.redFighter.name} {oddsLabel(market.redOddsBps)} vs {market.fight.blueFighter.name} {oddsLabel(market.blueOddsBps)}</strong></div><b>{market.status}</b><select name="operation" defaultValue={market.status === "OPEN" ? "LOCK" : market.status === "LOCKED" ? "SETTLE" : "VOID"} disabled={market.status === "SETTLED" || market.status === "VOID"}><option value="LOCK">Lock</option><option value="REOPEN">Reopen</option><option value="SETTLE">Settle from result</option><option value="VOID">Void and refund</option></select><button className="button button-small" disabled={market.status === "SETTLED" || market.status === "VOID"} type="submit">Apply</button></form>)}</section></main>;
}
