import type { Metadata } from "next";
import { updateUserRoleAction, updateUserStatusAction } from "@/features/admin/operations.actions";
import { prisma } from "@/lib/prisma";

export const metadata: Metadata = { title: "Users and roles" };

export default async function AdminUsersPage({ searchParams }: { searchParams: Promise<{ notice?: string; error?: string; q?: string }> }) {
  const query = await searchParams;
  const users = await prisma.user.findMany({ where: query.q ? { OR: [{ displayName: { contains: query.q, mode: "insensitive" } }, { email: { contains: query.q, mode: "insensitive" } }] } : undefined, include: { roles: true, wallet: true, fighterProfile: true }, orderBy: { createdAt: "desc" }, take: 100 });
  return <main className="admin-page"><div className="admin-title"><div><p>Identity operations</p><h1>Users and roles</h1></div><span>High-impact changes require a reason and confirmation</span></div>{query.notice && <p className="admin-notice">{query.notice}</p>}{query.error && <p className="admin-error">{query.error}</p>}<form className="admin-search"><input defaultValue={query.q ?? ""} name="q" placeholder="Search display name or email" /><button className="button button-ghost">Search</button></form><section className="admin-user-list">{users.map((user) => <article className="admin-panel" key={user.id}><header><div><strong>{user.displayName ?? user.name ?? "Unnamed player"}</strong><small>{user.email ?? "Discord account"} · Joined {user.createdAt.toLocaleDateString("en-US")}</small></div><b className={`user-${user.status.toLowerCase()}`}>{user.status}</b></header><div className="user-facts"><span>Balance <strong>{user.wallet?.balance.toLocaleString() ?? "0"}</strong></span><span>Roles <strong>{user.roles.map(({ role }) => role).join(", ") || "None"}</strong></span><span>Fighter <strong>{user.fighterProfile ? `#${user.fighterProfile.rank ?? "–"} ${user.fighterProfile.name}` : "No"}</strong></span></div><details><summary>Change status</summary><form action={updateUserStatusAction} className="admin-form"><input name="userId" type="hidden" value={user.id} /><label>New status<select defaultValue={user.status === "SUSPENDED" ? "ACTIVE" : "SUSPENDED"} name="status"><option value="ACTIVE">Active</option><option value="SUSPENDED">Suspended</option></select></label><label>Reason<textarea name="reason" minLength={10} maxLength={300} required /></label><label>Type CONFIRM<input name="confirmation" required /></label><button className="button button-primary">Apply status</button></form></details><details><summary>Change role</summary><form action={updateUserRoleAction} className="admin-form"><input name="userId" type="hidden" value={user.id} /><div className="form-row"><label>Role<select name="role"><option value="MODERATOR">Moderator</option><option value="ADMIN">Admin</option></select></label><label>Operation<select name="operation"><option value="GRANT">Grant</option><option value="REVOKE">Revoke</option></select></label></div><label>Reason<textarea name="reason" minLength={10} maxLength={300} required /></label><label>Type CONFIRM<input name="confirmation" required /></label><button className="button button-primary">Apply role</button></form></details></article>)}</section></main>;
}
