import type { Metadata } from "next";
import Link from "next/link";
import type { CardRarity, Prisma } from "@/generated/prisma/client";
import { SiteHeader } from "@/components/site-header";
import { Crown } from "@/components/crown";
import { CollectibleCard } from "@/features/cards/collectible-card";
import { prisma } from "@/lib/prisma";

export const metadata: Metadata = { title: "Card marketplace" };
export const dynamic = "force-dynamic";

export default async function MarketPage({ searchParams }: { searchParams: Promise<{ rarity?: string; set?: string; sort?: string }> }) {
  const filters = await searchParams;
  const rarity = ["COMMON", "RARE", "EPIC", "LEGENDARY"].includes(filters.rarity ?? "") ? filters.rarity as CardRarity : undefined;
  const where: Prisma.MarketListingWhereInput = { status: "ACTIVE", ...(rarity ? { card: { definition: { rarity } } } : {}), ...(filters.set ? { card: { definition: { setId: filters.set } } } : {}) };
  const orderBy: Prisma.MarketListingOrderByWithRelationInput = filters.sort === "price-asc" ? { price: "asc" } : filters.sort === "price-desc" ? { price: "desc" } : { createdAt: "desc" };
  const [listings, sets, recentSales] = await Promise.all([prisma.marketListing.findMany({ where, include: { card: { include: { definition: { include: { set: true } } } }, seller: { select: { displayName: true } } }, orderBy, take: 60 }), prisma.cardSet.findMany({ where: { active: true }, orderBy: { releasedAt: "desc" } }), prisma.marketSale.findMany({ include: { card: { include: { definition: true } } }, orderBy: { createdAt: "desc" }, take: 8 })]);
  return <main className="market-page"><SiteHeader /><section className="market-hero"><p className="eyebrow"><span /> Collector exchange</p><h1>The Realm Market</h1><p>Buy unique cards directly from other collectors. Launch fee: 0%.</p><Link className="button button-primary" href="/market/mine">Sell from your collection</Link></section><form className="market-filters"><label>Rarity<select defaultValue={rarity ?? ""} name="rarity"><option value="">All rarities</option><option>COMMON</option><option>RARE</option><option>EPIC</option><option>LEGENDARY</option></select></label><label>Set<select defaultValue={filters.set ?? ""} name="set"><option value="">All sets</option>{sets.map((set) => <option key={set.id} value={set.id}>{set.code} · {set.name}</option>)}</select></label><label>Sort<select defaultValue={filters.sort ?? "recent"} name="sort"><option value="recent">Recently listed</option><option value="price-asc">Price low to high</option><option value="price-desc">Price high to low</option></select></label><button className="button button-ghost">Apply filters</button></form><section className="market-listings"><div className="section-heading"><div><p className="eyebrow"><span /> Active listings</p><h2>{listings.length} cards available</h2></div></div>{listings.length ? <div className="market-grid">{listings.map((listing) => <Link href={`/market/${listing.id}`} key={listing.id}><CollectibleCard card={{ name: listing.card.definition.name, subtitle: listing.card.definition.subtitle, rarity: listing.card.definition.rarity, serialNumber: listing.card.serialNumber, setCode: listing.card.definition.set.code, cardNumber: listing.card.definition.cardNumber, imageUrl: listing.card.definition.imageUrl }} /><div className="listing-meta"><span>{listing.seller.displayName ?? "RFL Collector"}</span><strong>{listing.price.toLocaleString()} <Crown /></strong></div></Link>)}</div> : <div className="market-empty"><h3>No cards match these filters.</h3><p>Try another rarity or return when collectors add new listings.</p></div>}</section>{recentSales.length > 0 && <section className="recent-sales"><h2>Recent sales</h2>{recentSales.map((sale) => <div key={sale.id}><span>{sale.card.definition.name} · Serial #{String(sale.card.serialNumber).padStart(6, "0")}</span><strong>{sale.price.toLocaleString()} Crowns</strong></div>)}</section>}</main>;
}
