import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";

export const metadata: Metadata = { title: "Terms and Conditions" };

export default function TermsPage() {
  return (
    <LegalPage eyebrow="Legal" title="Terms and Conditions">
      <section><h2>1. Agreement and eligibility</h2><p>These Terms govern access to PlayRFL.com and Realm Fighting League (“RFL”). By creating or using an account, you agree to these Terms and the Privacy Policy. You must be at least 13 years old. You must provide an accurate date of birth. Crown wagering, fight betting, Coin Flip, Blackjack, and High-Low are restricted to users who report that they are at least 18 years old.</p></section>
      <section><h2>2. Accounts</h2><p>RFL uses Discord OAuth and does not issue passwords. You are responsible for your Discord account and activity through your RFL account. Do not impersonate others, evade restrictions, transfer access, or provide false eligibility information. RFL may change or reject display names that are deceptive, infringing, or abusive.</p></section>
      <section><h2>3. Community and competition rules</h2><p>You may not cheat, fix matches, collude, harass others, exploit bugs, interfere with the service, automate gameplay without written permission, manipulate outcomes, or use unauthorized bots. Report exploitable defects privately. RFL may void results, wagers, listings, or rewards and may suspend or terminate accounts to protect players and competition integrity.</p></section>
      <section><h2>4. Crowns and virtual items</h2><p>Crowns, cards, packs, rankings, and other virtual items are limited licenses within RFL. They are not money or property, have no cash value, cannot be purchased for cash on the current service, and cannot be redeemed or exchanged outside RFL. RFL may correct balances affected by error, abuse, fraud, reversals, or administrative mistakes.</p></section>
      <section><h2>5. Casino and fight betting</h2><p>All current games and betting use only virtual Crowns. No real-money gambling is offered. Outcomes, odds, limits, and payouts are controlled by the displayed rules and service configuration. Participation can result in loss of Crowns. Age eligibility does not guarantee access; RFL may close markets, void activity, impose limits, or disable features.</p></section>
      <section><h2>6. Cards and marketplace</h2><p>Cards are virtual collectibles recorded in RFL’s database. Marketplace transactions use Crowns only. Listings must be genuine and may not be used for collusion, manipulation, laundering, or off-platform sale. Artwork and RFL branding remain owned by their respective rights holders; possession of a virtual card does not transfer copyright.</p></section>
      <section><h2>7. User content and intellectual property</h2><p>You retain rights you hold in content you submit and give RFL a non-exclusive license to host, display, reproduce, and moderate it as needed to operate and promote the service. Do not submit content you lack permission to use. RFL’s software, branding, artwork, and original materials are protected by applicable law.</p></section>
      <section><h2>8. Availability and changes</h2><p>RFL may change, suspend, maintain, or discontinue features, including beta features, without guaranteeing uninterrupted availability. Data loss, outages, Discord failures, and third-party service failures are possible. Do not rely on virtual balances or records as having real-world value.</p></section>
      <section><h2>9. Disclaimers and liability</h2><p>To the maximum extent permitted by law, RFL is provided “as is” without warranties of uninterrupted, error-free, or secure operation. RFL and its operators will not be liable for indirect, incidental, special, consequential, or punitive damages, or loss of virtual items, arising from use of the service. Rights that cannot legally be waived remain unaffected.</p></section>
      <section><h2>10. Indemnification</h2><p>To the extent permitted by law, you agree to defend and indemnify RFL and its operators from third-party claims caused by your unlawful conduct, infringement, misuse of the service, or violation of these Terms.</p></section>
      <section><h2>11. Disputes and governing law</h2><p>Before filing a claim, contact RFL and allow 30 days for informal resolution. These Terms are governed by Texas law, excluding conflict-of-law rules. Unless applicable law requires otherwise, disputes must be brought in a court with jurisdiction in Texas. No arbitration agreement is imposed by this version.</p></section>
      <section><h2>12. Changes and entire agreement</h2><p>RFL may update these Terms. Material revisions may require renewed acceptance. If a provision is unenforceable, the remainder continues. These Terms, the Privacy Policy, and applicable posted feature policies are the entire agreement concerning the service.</p></section>
    </LegalPage>
  );
}
